# Robot joint limits configuration for Staubli TX2-60
joint_limits:
  joint_1:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_effort: 126.0
    min_position: !degrees -180.0
    max_position: !degrees 180.0
    max_velocity: !degrees 300.0
    max_acceleration: !degrees 1000.0
  joint_2:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_effort: 47.0
    min_position: !degrees -127.0
    max_position: !degrees 127.0
    max_velocity: !degrees 300.0
    max_acceleration: !degrees 1000.0
  joint_3:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_effort: 32.0
    min_position: !degrees -150.0
    max_position: !degrees 150.0
    max_velocity: !degrees 300.0
    max_acceleration: !degrees 1000.0
  joint_4:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_effort: 7.0
    min_position: !degrees -270.0
    max_position: !degrees 270.0
    max_velocity: !degrees 300.0
    max_acceleration: !degrees 1000.0
  joint_5:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_effort: 8.0
    min_position: !degrees -120.0
    max_position: !degrees 120.0
    max_velocity: !degrees 300.0
    max_acceleration: !degrees 1000.0
  joint_6:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_effort: 2.0
    min_position: !degrees -270.0
    max_position: !degrees 270.0
    max_velocity: !degrees 500.0
    max_acceleration: !degrees 3000.0
