# Robot mesh configuration for Staubli TX2-60
meshes:
  base_link:
    visual:
      package: staubli_robot_description
      path: meshes/tx2_60/visual/base_link.dae
    collision:
      package: staubli_robot_description
      path: meshes/tx2_60/collision/base_link.stl
  link_1:
    visual:
      package: staubli_robot_description
      path: meshes/tx2_60/visual/link_1.dae
    collision:
      package: staubli_robot_description
      path: meshes/tx2_60/collision/link_1.stl
  link_2:
    visual:
      package: staubli_robot_description
      path: meshes/tx2_60/visual/link_2.stl
      origin:
        xyz: 0 -0.11735 0
        rpy: 0 0 0
      material: staubli_yellow
    collision:
      package: staubli_robot_description
      path: meshes/tx2_60/collision/link_2.stl
      origin:
        xyz: 0 -0.11735 0
        rpy: 0 0 0
  link_3:
    visual:
      package: staubli_robot_description
      path: meshes/tx2_60/visual/link_3.dae
    collision:
      package: staubli_robot_description
      path: meshes/tx2_60/collision/link_3.stl
  link_4:
    visual:
      package: staubli_robot_description
      path: meshes/tx2_60/visual/link_4.stl
      origin:
        xyz: 0 0 -0.088
        rpy: 0 0 0
      material: staubli_yellow
    collision:
      package: staubli_robot_description
      path: meshes/tx2_60/collision/link_4.stl
      origin:
        xyz: 0 0 -0.088
        rpy: 0 0 0
  link_5:
    visual:
      package: staubli_robot_description
      path: meshes/tx2_60/visual/link_5.dae
    collision:
      package: staubli_robot_description
      path: meshes/tx2_60/collision/link_5.stl
  link_6:
    visual:
      package: staubli_robot_description
      path: meshes/tx2_60/visual/link_6.dae
    collision:
      package: staubli_robot_description
      path: meshes/tx2_60/collision/link_6.stl