name: Documentation

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -y -qq python3-sphinx doxygen doxygen-gui doxygen-doc graphviz tree dvisvgm dvipng
            sudo apt-get install -y -qq texlive-latex-extra
            cd ./staubli_driver_ros2/
            pip install -r requirements.txt

      - name: Build documentation
        run: |
            cd ./staubli_driver_ros2
            sphinx-build -b html sphinx sphinx/_build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5 # or specific "vX.X.X" version tag for this action
        with:
          path: staubli_driver_ros2/sphinx/_build/

  # Deployment job
  deploy_documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_documentation
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
